SUPABASE_URL = "https://kxfbkqfswyuzmwfmnfnc.supabase.co"
SUPABASE_KEY = "sb_publishable_n5Wz6tvlvBxrkgxKYJQ7Jg_VqkmwP61"

# CREDENCIALES GMAIL
GMAIL_USER = "diego@sievert.com.co"
GMAIL_PASSWORD = "ypmd kvem zjlw qapt"
EMAIL_DESTINO_INTERNO = "diego@sievert.com.co" # A qui√©n le llega la alerta en la empresa